language: python
python:
    - '2.6'
    - '2.7'
    - '3.2'
    - '3.3'
    - '3.4'
    - '3.5'
    - nightly
script:
    - test AWESOME_DOBESTAN
notifications:
  slack:
    secure: GtpdC3uIUXtKK4V1PBM36mq2tf4HtvKYgG6MBUyPMUX6hWES4o4G394C0Q3HxJ5dqCVDtetgriwKQMl31fp4Cx3+ZIX/dZdED9ClEi6aEmPwEd9+e4n41mhIAHGQNm+cPb/ZY1glg++8RHmrty2S6/agM4lGbKOVSM0Rl3ju+fpALzy7xPK5g3O0uAF4ltGBslZlf0+YcjSVNYlCoXtRRupvgIXodUowyz6pjXYOGR93D2qnKaVK/9v/+BdvujA5YNbrZYOV5v6chPQAyLSw7Cr3607fC/r0q+P1XxWDvWVYUcR/lMs4fEWP9bW29I5LmWUHiVIh6tslZd1wFrvM/hgCvyvEcSQyrE4/KdwNMcX60HvMsWddkQ5vSqLzR222XKvWDgG17P/mIiD4ZenRGXZeNVe/+OqPINZLUTPAibBGMp/4GIsPOAB2pbpl1fzxHcCHVt4Hax7T0INNPHHmwasr9+Alz1X/U8bS03wU94d3UxTAEgZZPqTDJ82LRacXtZ76LXria2jlZ4Ci/GZC/OkV7NXQfOIjN5pjCLGs0PBNEXfCeqfaZnr/g1rP5lJ41GAZ6haOA/6wtZgnDL7Hn4QU6E9ru7Kjq8imSWemvIyc0t3dGWHb4ioC3PRu2b8nqc1duXcjjWNQRNEpk89hl3lIOuOyGVPCw0+mUN5hGUE=
